version: '2'
services:
  grafana_graphite:
    build: .
    image: johnmetta/grafanyx
    container_name: grafanyx
    ports:
      - '8080:8080'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - /var/data/whisper:/opt/graphite/storage/whisper
      - /var/data/grafana:/opt/grafana/data
      - /var/log/graphite:/opt/graphite/storage/log
      - /var/log/supervisor:/var/log/supervisor
